[package]
name = "rust_kirigami_calc"
version = "0.3.0"
edition = "2021"
rust-version = "1.85"

[dependencies]
cxx = "1.0"
cxx-qt = "0.10"
cxx-qt-lib = { version = "0.10", features = ["qt_full"] }
exmex = "0.21"

[build-dependencies]
cxx-qt-build = "0.10"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
